# Generated by Django 2.2.14 on 2021-02-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='date',
            new_name='create',
        ),
    ]
